### PR TITLE
upgrade pandoc to version 2.14

### PR DESCRIPTION
**Pull request by dhimmel**
supersedes https://github.com/manubot/rootstock/pull/386

### CODE REVIEW

**Comment by dhimmel** [comment]
Could also make this pandoc 2.14 if https://github.com/conda-forge/pandoc-feedstock/pull/90 is merged soon.

**Comment by dhimmel** [comment]
This PR updates pandoc and it appears the tooltip plugin stops working. Take a look at https://ci.appveyor.com/api/buildjobs/v8df0g3o4vq6pagw/artifacts/manuscript-1.0.236-a6d315c.html.

The HTML for citations looks the same to me. With pandoc 2.13:

```html
<p>Citation by DOI <span class="citation" data-cites="IhliSZDo">[<a href="#ref-IhliSZDo" role="doc-biblioref">1</a>]</span>.</p>
```

Before:

https://github.com/manubot/rootstock/blob/5be899e85e98408187a55cb57b8354fc11751312/manuscript.html#L233

But the HTML for references has changed. Now:

```html
<h2 class="page_break_before" id="references">References</h2>
<!-- Explicitly insert bibliography here -->
<div id="refs" class="references csl-bib-body" role="doc-bibliography">
<div id="ref-IhliSZDo" class="csl-entry" role="doc-biblioentry">
<div class="csl-left-margin">1. </div><div class="csl-right-inline"><strong>Sci-Hub provides access to nearly all scholarly literature</strong> <div class="csl-block">Daniel S Himmelstein, Ariel Rodriguez Romero, Jacob G Levernier, Thomas Anthony Munro, Stephen Reid McLaughlin, Bastian Greshake Tzovaras, Casey S Greene</div> <em>eLife</em> (2018-03-01) <a href="https://doi.org/ckcj">https://doi.org/ckcj</a> <div class="csl-block">DOI: <a href="https://doi.org/10.7554/elife.32822">10.7554/elife.32822</a> · PMID: <a href="https://www.ncbi.nlm.nih.gov/pubmed/29424689">29424689</a> · PMCID: <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5832410">PMC5832410</a></div></div>
</div>
```

Before:

https://github.com/manubot/rootstock/blob/5be899e85e98408187a55cb57b8354fc11751312/manuscript.html#L457-L465

@vincerubinetti would you be able to take a look and see if the tooltip plugin needs any changes for the new HTML? If so, you can make a PR into this PR

**Comment by dhimmel** [comment]
I upgraded pandoc in this PR to 2.14 ([release notes](https://github.com/jgm/pandoc/releases/tag/2.14)) which includes https://github.com/jgm/pandoc/commit/3f09f53459b877f53072efbf57dec21fa37280b5. We can use [more recent HTML](https://ci.appveyor.com/api/buildjobs/k6u1imoonqssmuvm/artifacts/manuscript-1.0.242-fd7ff49.html) to prototype the tooltip updates.

**Comment by vincerubinetti** [comment]
@dhimmel will do this tomorrow 🤖

**Comment by vincerubinetti** [comment]
Some notes as I work through this:

https://github.com/manubot/rootstock/blob/main/build/plugins/tooltips.html#L232 needs to add `"class"`.

https://github.com/manubot/rootstock/blob/main/build/plugins/tooltips.html#L339 change `querySelector("p")` to `querySelector(":nth-child(2)")`

Table references are also broken:

image

"jump to" plugin broken for references:

image

And references CSS needs some tweaking. Indent is too large, and no spacing between entries.

**Comment by vincerubinetti** [comment]
@dhimmel can you give me access to push commits to `dhimmel:pandoc-2.13`. There are more changes required here than I thought.

**Comment by dhimmel** [comment]
@vincerubinetti perhaps you can create a branch based off of this PR's branch and then make as many commits as you'd like to that branch. I can then make the PR from your branch to `dhimmel:pandoc-2.13`.

Do you have your own fork of rootstock currently? If you have your own fork that you've cloned locally, then you can do:

```bash
git checkout -b dhimmel-pandoc-2.13 main
git pull https://github.com/dhimmel/manubot-rootstock.git pandoc-2.13
# make commits
# push
```

I want to avoid adding extra branches to this repo, since that can hamper the demonstrative nature of it. Let me know if you hit any snags. Happy to jump on a quick call to debug any git issues.

**Comment by vincerubinetti** [comment]
Sorry for the delay, I needed to get Manubot actually running on my Windows machine before I could tackle this (was able to do that with WSL).

One thing I noticed is this (with all plugins and themes disabled):
image

`id`'s are supposed to be unique to the document. This is an error in the table-nos plugin and I believe is what is causing the double anchors and buttons.

**Comment by vincerubinetti** [comment]
#427

**Comment by dhimmel** [comment]
Closing this, since we can merge https://github.com/manubot/rootstock/pull/427 instead

**Pull request closed without merging**
