### PR TITLE
[stub] support alternate HTML theme through environment variable

### PR DESCRIPTION
**Pull request by michaelmhoffman**
Change to `build.sh` demonstrating potential solution to #112.

### CODE REVIEW

**Comment by agitter** [comment]
I like this design.  We should consider doing the same for `CSL_PATH`, `BIBLIOGRAPHY_PATH`, and `INPUT_PATH`.

**Comment by dhimmel** [comment]
Noting that if we adopt `pandoc --defaults` as proposed in https://github.com/manubot/rootstock/pull/290, this method of setting pandoc options through environment variables will no longer work.

**Comment by michaelmhoffman** [comment]
```
PANDOC_DEFAULTS_PATH="${PANDOC_DEFAULTS_PATH:-build/pandoc-defaults.yaml}"
```

**Comment by dhimmel** [comment]
We merged https://github.com/manubot/rootstock/pull/290, which includes something similar to @michaelmhoffman's suggestion:

https://github.com/manubot/rootstock/blob/06fb01d0c8e5c1ca7632cd17c27d3fddd0691386/build/build.sh#L22-L24

Now that we're using `--defaults` files, this PR is less relevant, so am closing it.

To customize pandoc's behavior, you can either edit the relevant line a default YAML file, or create a new pandoc-defaults directory and change `PANDOC_DEFAULTS_DIR` as discussed at https://github.com/manubot/rootstock/pull/290#discussion_r362842345.

**Pull request closed without merging**
