### PR TITLE
Update Pandoc to 2.10

### PR DESCRIPTION
**Pull request by dhimmel**
Update other dependencies that aren't held back due to weasyprint/
ciaro to latest on 2020-07-02

https://github.com/jgm/pandoc/releases/tag/2.10

### CODE REVIEW

**Comment by dhimmel** [comment]
Looking through the Pandoc changes at https://github.com/jgm/pandoc/releases/tag/2.10

>  HTML writer:
> -   Use CSS in favor of `<br>` for display math ([#6372](https://github.com/jgm/pandoc/pull/6372)) Some CSS to ensure that display math is displayed centered and on a new line is now included in the default HTML-based templates; this may be overridden if the user wants a different behavior.

> -   Docx writer:
> -   Enable column and row bands for tables ([#6371](https://github.com/jgm/pandoc/issues/6371)). This change will not have any effect with the default style. However, it enables users to use a style (via a reference.docx) that turns on row and/or column bands.

@vincerubinetti do any of those sound problematic?

**Comment by dhimmel** [comment]
Failed due to a pandoc-fignos error (the AST must have changed):

```
[INFO] Running filter pandoc-fignos
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/manubot/bin/pandoc-fignos", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandoc_fignos.py", line 645, in main
    altered)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandoc_fignos.py", line 642, in <lambda>
    altered = functools.reduce(lambda x, action: walk(x, action, fmt, meta),
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 844, in process_refs
    _process_refs(value[-5], pattern, labels)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 92, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 746, in _process_refs
    if v['t'] == 'Cite' and len(v['c']) == 2:
TypeError: string indices must be integers
Error running filter pandoc-fignos:
Filter returned error status 1
```

**Comment by lierdakil** [comment]
FWIW, pandoc-crossref was updated to support pandoc 2.10. Saying this so you know you have options in case pandoc-xnos doesn't update in the near future.

**Comment by dhimmel** [comment]
pandoc-xnos should be updated soon as per https://github.com/tomduck/pandoc-xnos/issues/16#issuecomment-665251621.

Linking to https://github.com/sergiocorreia/panflute/issues/142, which has a bunch of info about how the Pandoc AST changed for 2.10. Once we can produce HTML output, we should check that our javascript plugins still work.

> FWIW, pandoc-crossref was updated to support pandoc 2.10

@lierdakil thanks for the info. Peeked at https://github.com/lierdakil/pandoc-crossref/commit/aeef943f8164df92a02a5906377743ded291cf3e. I see that pandoc-crossref can now be [installed with conda](https://anaconda.org/conda-forge/pandoc-crossref). This makes it more feasible for us to include it.

**Comment by dhimmel** [comment]
Upgraded pandoc-xnos in ba6337087f749d03f008f7049a6386390ac685ad, but now am running into [an error](https://github.com/manubot/rootstock/pull/354/checks?check_run_id=929778030#step:7:64) from panflute: 


```python-traceback
[INFO] Running filter pandoc-manubot-cite
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/manubot/bin/pandoc-manubot-cite", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/manubot/pandoc/cite_filter.py", line 214, in main
    doc = pf.load(input_stream=args.input)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/io.py", line 59, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/elements.py", line 1532, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: Caption
Error running filter pandoc-manubot-cite:
Filter returned error status 1
##[error]Process completed with exit code 83.
```

I think https://github.com/sergiocorreia/panflute/issues/142 is the issue to monitor for this being fixed upstream.

**Comment by dhimmel** [comment]
panflute still hasn't been upgraded. ported some of the non-pandoc environment updates to https://github.com/manubot/rootstock/pull/383.

**Comment by dhimmel** [comment]
https://github.com/sergiocorreia/panflute/issues/142 is closed with https://pypi.org/project/panflute/2.0.3/ released to support Pandoc 2.11. I am going to close this PR and open a new one for pandoc 2.11 support.

**Pull request closed without merging**
