### PR TITLE
Defer ai-editor documentation to dedicated repo

### PR DESCRIPTION
**Pull request by vincerubinetti**

### CODE REVIEW

**Comment by vincerubinetti** [comment]
yes, please hold off on merging. We still need to work on the documentation in the editor repo some more

**Comment by agitter** [comment]
@vincerubinetti do you think the USAGE.md here has gotten too long and complex? The AI workflow is part of this repo, so I'm wondering about the motivation for moving the documentation. I'm not against it but want to understand your thought process. about how we'll manage these.

Making sure @miltondp sees this too.

**Comment by agitter** [comment]
Thanks, that's helpful. If the `ai-revision.yaml` workflow was going to have frequent updates anyway, then it would make sense to keep the corresponding detailed documentation here. However, that workflow file is fairly straightforward so most updates will likely happen in the `manubot-ai-editor` repo. I lean toward making this change.

**Comment by miltondp** [comment]
The team working on the Manubot AI Editor decided it would make more sense to have its documentation on a repo that we control more directly, and we also discussed several of the reasons @vincerubinetti already mentioned. As the Manubot AI Editor code stabilizes, we can decide how to proceed, but for now I would move the documentation. The merging should happen when we have the documentation ready on the `manubot/manubot-ai-editor` repo.

**Comment by vincerubinetti** [comment]
Now that https://github.com/manubot/manubot-ai-editor/pull/42 is merged, I think this is ready to merge.

**Comment by vincerubinetti** [comment]
Followup: https://github.com/manubot/manubot-ai-editor/pull/44

**Pull request merged**
