### PR TITLE
Output

### PR DESCRIPTION
**Pull request by laurentperrinet**

### CODE REVIEW

**Comment by laurentperrinet** [comment]
sorry for this unwanted PR :-)

**Comment by agitter** [comment]
It's no trouble.  Let us know if you'd like any assistance with https://github.com/laurentperrinet/2019_illusions-visuelles

**Comment by laurentperrinet** [comment]
Thanks for your kind message. I tried to go too fast, then did run into problems. Erased the repository, started from scratch, then followed the instructions in `USAGE.md` and now everything works perfectly @ https://github.com/laurentperrinet/2019-05_illusions-visuelles .

**Comment by dhimmel** [comment]
@laurentperrinet good to hear! I think this is an exciting milestone... the first Manubot [document](https://laurentperrinet.github.io/2019-05_illusions-visuelles/v/294f4534a8a645ebd011c49253c9008d835341ae/#abstract) in French (or any language besides English as far as I know).

**Comment by laurentperrinet** [comment]
FYI: this short paper was published in
https://theconversation.com/illusions-et-hallucinations-visuelles-une-porte-sur-la-perception-117389 
(english translation @ http://translate.google.com/translate?js=n&sl=auto&tl=en&u=https://theconversation.com/illusions-et-hallucinations-visuelles-une-porte-sur-la-perception-117389 )
(more details @ https://laurentperrinet.github.io/post/2019-06-06-theconversation/ ... in french)

**Pull request closed without merging**
