### PR TITLE
Use Athena to build PDF, if Docker is installed

### PR DESCRIPTION
**Pull request by dhimmel**
Closes https://github.com/manubot/rootstock/issues/170

More information about Athena is available at
https://github.com/arachnys/athenapdf

Apply feature from meta-review commit:
https://github.com/greenelab/meta-review/commit/cffcfeaea0b6859051d16ab1e263d8bcf62a24b1

This commit was created with the command:
```
curl https://github.com/greenelab/meta-review/commit/cffcfeaea0b6859051d16ab1e263d8bcf62a24b1.patch | git apply
```

### CODE REVIEW

**Comment by dhimmel** [comment]
Would be good to get a macOS test. @slochower do you use mac and does the Docker control flow work, like:
```
DOCKER_EXISTS=`command -v docker`
````

**Comment by slochower** [comment]
Yep.

```
Wed Apr 17 15:08:22 Triceratops:~
$ command -v docker
/usr/local/bin/docker
```

**Comment by agitter** [comment]
We could use Travis CI to test macOS without Docker.  They support macOS but [not Docker for macOS](https://docs.travis-ci.com/user/docker/).

This new build script may also bring us closer to Windows compatibility, working around some issues in #144.

**Comment by dhimmel** [comment]
> We could use Travis CI to test macOS without Docker

With the current design of roostock, I don't think this makes sense, since it will double the number of CI builds for manuscript instances. However, we perhaps should look into macOS builds for https://github.com/manubot/manubot. Or think about future ways we can create a testing manuscript that performs additional tests beyond the template of rootstock.

> This new build script may also bring us closer to Windows compatibility

@agitter if WeasyPrint and its `pango` dependency is the sole thing preventing Windows environment compatibility, does your calculus from https://github.com/manubot/rootstock/issues/170#issuecomment-484182440 change. I.e. would you want to require docker for PDF creation?

**Comment by agitter** [comment]
> it will double the number of CI builds for manuscript instances

Sorry, I didn't explain myself well enough.  I was thinking that we could create a temporary branch / pull request for one time testing of this build script in a clean macOS environment on Travis.  If anyone else is willing to test locally on macOS without Docker, that wouldn't be necessary.

Despite my comment above, Windows support doesn't change my thoughts in #170 much regarding requiring Docker for PDF builds.  Because we haven't confirmed Manubot setup works in Windows with Docker, I expect local PDF builds on Windows are going to be in limited demand.  I am assuming there are more Linux / macOS users who would want local PDFs without Docker than there are Windows users.

My understanding is that couldn't have local PDF builds on Windows unless we remove the WeasyPrint dependency from the environment and require Docker.

**Comment by dhimmel** [comment]
>  I am assuming there are more Linux / macOS users who would want local PDFs without Docker than there are Windows users.

Okay we can keep WeasyPrint, with the cost of not being able to create a windows-compatible `environment.yml`.

> Don't have a Mac without Docker, to test what happens then

Can you just change 

```
DOCKER_EXISTS=`command -v docker`
```

to

```
DOCKER_EXISTS=`command -v dockerxxx`
```

And then see whether the the WeasyPrint PDF creation executes and succeeds, and that the Athena PDF creation does not execute?

**Comment by slochower** [comment]
Looks good. Do get one warning, though:

```
cp: the -H, -L, and -P options may not be specified with the -r option.
```

Maybe we want `cp -R -L`. The man page does specify `-R` for recursive, but I always use `-r` from habit on linux and it must work through some compatibility.

**Comment by dhimmel** [comment]
Looks like the [linux command](http://man7.org/linux/man-pages/man1/cp.1.html), `-R`, `-r`, or `--recursive`. However, macOS only [supports](https://ss64.com/osx/cp.html) `-R`. So yeah we should switch this.

**Comment by dhimmel** [comment]
@agitter any remaining requests on your end? It wasn't clear whether you wanted addition macOS testing or whether slochower's empirical testing is enough.

**Comment by slochower** [comment]
I'm getting some issues with Athena. I'm wondering if it might be related to the plugins. I've asked to get more output from the build process so I can debug what's going on. Ref: https://github.com/arachnys/athenapdf/issues/195

**Comment by slochower** [comment]
Tried to eliminate plugins as a cause. Rendering the HTML like so still causes Athena to crash:

```
pandoc --verbose \
  --from=markdown \
  --to=html5 \
  --filter=pandoc-eqnos \
  --filter=pandoc-tablenos \
  --filter=pandoc-fignos \
  --bibliography=$BIBLIOGRAPHY_PATH \
  --csl=$CSL_PATH \
  --metadata link-citations=true \
    --output=output/manuscript.html \
  $INPUT_PATH

  # --include-after-body=build/themes/default.html \
  # --include-after-body=build/plugins/table-scroll.html \
  # --include-after-body=build/plugins/anchors.html \
  # --include-after-body=build/plugins/accordion.html \
  # --include-after-body=build/plugins/tooltips.html \
  # --include-after-body=build/plugins/jump-to-first.html \
  # --include-after-body=build/plugins/link-highlight.html \
  # --include-after-body=build/plugins/table-of-contents.html \
  # --include-after-body=build/plugins/lightbox.html \
  # --mathjax \
  # --variable math="" \
  # --include-after-body=build/plugins/math.html \
  # --include-after-body=build/plugins/hypothesis.html \
  # --include-after-body=build/plugins/analytics.html \

```

**Comment by slochower** [comment]
@dhimmel to help the Athena folks with debugging, I would have thought to point them to `manuscript.html` on the `output` GitHub branch, but that of course doesn't have the images or plugins locally. Is it `index.html` on the `gh-pages` branch?

**Comment by dhimmel** [comment]
I see in the [Travis logs](https://travis-ci.org/slochower/smirnoff-host-guest-manuscript/builds/530392091#L2296) that the athena command failed with the message `The renderer process has crashed.` 

> @dhimmel to help the Athena folks with debugging, I would have thought to point them to manuscript.html on the output GitHub branch

You are right that athena is actually being run on `output/manuscript.html`. However, there should be very few differences to index.html on the `gh-pages` branch / `webpage` directory. In your case, I think [this versioned GitHub Pages URL](https://slochower.github.io/smirnoff-host-guest-manuscript/v/5c9b6058fb44adba5c97a646ebccc801d566393e/) is sufficient for athena debugging. When I enter it at https://www.athenapdf.com/ I get the error message:

> There was a problem converting this page, please try again or try another URL

**Comment by slochower** [comment]
@dhimmel note: https://github.com/arachnys/athenapdf/issues/195#issuecomment-491075361

Unless you have qualms, I'll make a PR to `--shm-size="2g"` to `build.sh`.

**Pull request merged**
