### PR TITLE
Export basic LaTeX manuscript

### PR DESCRIPTION
**Pull request by dhimmel**
refs https://github.com/manubot/rootstock/issues/249

### CODE REVIEW

**Comment by dhimmel** [comment]
# manuscript.tex snippets

Here are parts of the output `manuscript.tex` separated by `...`:

```tex
\begin{figure}
\hypertarget{fig:wide-image}{%
\centering
\includegraphics{https://github.com/manubot/resources/raw/15493970f8882fce22bef829619d3fb37a613ba5/test/wide.png}
\caption{\textbf{An image too wide to fit within page at full size.}
Loaded from a specific (hashed) version of the image on GitHub.}\label{fig:wide-image}
}
\end{figure}
...
Citation by DOI {[}\protect\hyperlink{ref-IhliSZDo}{1}{]}.
...
A LaTeX equation:

\begin{equation}\int_0^\infty e^{-x^2} dx=\frac{\sqrt{\pi}}{2}\label{eq:regular-equation}\end{equation}
...
\leavevmode\hypertarget{ref-6acIRW4q}{}%
6. \textbf{Open collaborative writing with Manubot} \\
Daniel S. Himmelstein, Vincent Rubinetti, David R. Slochower, Dongbo Hu, Venkat S. Malladi, Casey S. Greene, Anthony Gitter\\
\emph{Manubot} (2020-05-25) \url{https://greenelab.github.io/meta-review/}
```

So looks like citations have been rendered, but figures are still references and not yet numbered.

**Comment by habi** [comment]
> So looks like citations have been rendered [...]

The main issue I always saw with submitting a final manuscript file as .tex is copying over the citations (from a Word or Markdown file) without introducing an error.
If the file *does* contain them that greatly minimizes any human errors!
I knew that I'd 'just' be able to `pandoc` the stuff together myself, but it's very convenient if the build pipleline does it automatically.

> [...] but figures are still references and not yet numbered.

That should be easy to take care of with a little bit of 'search-and-replace'.
I think it's much less error-prone than manually copy-pasting 40+ citations :)

**Comment by dhimmel** [comment]
@agitter do you see value in merging this and keeping BUILD_LATEX off by default?

**Comment by agitter** [comment]
> do you see value in merging this and keeping BUILD_LATEX off by default?

Yes, I think it's a small addition that won't clutter anything and can be a helpful starting point for LaTeX export.

I intend to comment on https://github.com/manubot/rootstock/issues/249 based on our LaTeX experience in https://github.com/greenelab/covid19-review/pull/943.  I now have a better understanding of the gaps between this basic export and what LaTeX authors may want.

**Review by agitter — APPROVED** [review]

**Pull request merged**
