### PR TITLE
Upgrade environment fully on 2021-11-29

### PR DESCRIPTION
**Pull request by dhimmel**
In the past we've had challenges trying to upgrade package versions one-by-one due to unresolvable conflicts. Therefore, I'm trying this new strategy to let conda set all the versions:

```bash
# remove existing conda environment
conda env remove --name manubot

# manually edit environment.yml to remove all pineed versions

# install environment letting conda resolve all versions
conda env create --file build/environment.yml

# Export full environment which includes all packages, versions, and build numbers (on Linux)
conda env export --name=manubot > build/environment-full.yml
```

The downside of this strategy is it will break if there were packages that we were intentionally holding back. I know we were holding weasyprint or its dependencies back, I think for Windows compatibility. 

TODO:

- [x] remove `build/environment-full.yml`
- [x] test local linux build using weasyprint: [manuscript.pdf](https://github.com/manubot/rootstock/files/7621673/manuscript.pdf)
- [x] test if the updated environment installs on windows
- [ ] test local windows build using weasyprint

### CODE REVIEW

**Comment by dhimmel** [comment]
Note the following from [build/README.md](https://github.com/manubot/rootstock/blob/8086a3985300c203353acbe44a2fc908f677d563/build/README.md?plain=1#L44-L45):

> The environment should successfully install on both Linux and macOS. However, it will fail on Windows due to the pango dependency.

We should remove this if the new environment now works on Windows.

**Comment by dhimmel** [comment]
This environment is building the manuscript without docker on linux and macos via GitHub actions! Windows builds work up to the WeasyPrint export where they hit https://github.com/conda-forge/weasyprint-feedstock/issues/31.

**Comment by agitter** [comment]
This looks like a smarter way to update dependencies without chasing down incompatible versions and having to fix them individually.  This latest environment gets closer to functional Windows builds than my previous attempt in #406.

When I test the environment file from 18091c8 locally in Windows, fontconfig 2.13.1 is supposedly installed.  I get the same error shown in GitHub Actions.  I'll follow up in the weasyprint issue.

If we're updating many package versions or major packages like pandoc, it would be nice to have a way to do regression testing.

**Comment by dhimmel** [comment]
> If we're updating many package versions or major packages like pandoc, it would be nice to have a way to do regression testing.

Yes very! But not sure how we'd make these tests.

**Comment by agitter** [comment]
It's tricky with this repository serving as a template.  We don't want to add tests here.

A better solution may be to have a separate repository that automatically tracks branches in the rootstock repository and runs CI tests with the updated rootstock.  I haven't set up a cross-repository workflow before, so I don't have a specific implementation in mind.

**Pull request merged**
