### PR TITLE
upgrade pandoc to version 2.11

### PR DESCRIPTION
**Pull request by dhimmel**
Supersedes https://github.com/manubot/rootstock/pull/354

### CODE REVIEW

**Comment by dhimmel** [comment]
Opened https://github.com/tomduck/pandoc-fignos/issues/85 regarding:

```
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/pandocxnos/core.py", line 873, in process_refs
    if value[-5]['c'][1]:
TypeError: list indices must be integers or slices, not str
```

**Comment by dhimmel** [comment]
New error https://github.com/manubot/rootstock/pull/386/checks?check_run_id=1381686742#step:7:75:

```python-traceback
[INFO] Running filter pandoc-manubot-cite
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/manubot/bin/pandoc-manubot-cite", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/manubot/pandoc/cite_filter.py", line 220, in main
    process_citations(doc)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/manubot/pandoc/cite_filter.py", line 206, in process_citations
    doc.metadata["references"] = citations.csl_items
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/elements.py", line 1072, in __setitem__
    self.content[i] = builtin2meta(v)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/elements.py", line 1394, in builtin2meta
    return _builtin_to_meta_func[type_](val) if type_ in _builtin_to_meta_func else val
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/elements.py", line 1387, in <lambda>
    list: lambda val: MetaList(*[builtin2meta(x) for x in val]),
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/elements.py", line 1016, in __init__
    self._set_content(args, MetaValue)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/base.py", line 120, in _set_content
    self._content = ListContainer(*value, oktypes=oktypes, parent=self)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/containers.py", line 47, in __init__
    self.extend(args)  # self.oktypes must be set first
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/_collections_abc.py", line 990, in extend
    self.append(v)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/_collections_abc.py", line 971, in append
    self.insert(len(self), value)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/containers.py", line 76, in insert
    v = check_type(v, self.oktypes)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/panflute/utils.py", line 71, in check_type
    raise TypeError(msg)
TypeError: 

Element "MetaList" received "CSL_Item" but expected <class 'panflute.base.MetaValue'>
```

**Comment by sergiocorreia** [comment]
The problem appears to lie here:

```
doc.metadata["references"] = citations.csl_items
```

It seems that only element that can contain citations is the `Cite` element. `Cite` is an Inline, and thus be contained within a MetaInline. That is:

```python
doc = Doc()
cite = Cite(citations=[citation])
doc.metadata['references'] = MetaInlines(cite)
```

This of course feels like a lot of trouble when you could also do:

```python
doc.references = [cite]
```

**Comment by dhimmel** [comment]
Thank you @sergiocorreia for commenting here! I want to make sure that we're on the same page regarding citations versus references.

The data we are writing to `doc.metadata["references"]` is bibliographic metadata for the citations. See [`references.json`](https://github.com/manubot/rootstock/blob/51aa10cbb0c7b6719c4c695716e72f5519c1fb98/references.json) as an example. In python typing parlance, references is of type `List[Dict[str, Any]]`, where each dictionary contains the CSL reference metadata for a citation.

> unless you are interested specifically in saving this externally through the metadata

From the [Pandoc docs](https://pandoc.org/MANUAL.html#option--citeproc):

> Citation processing will not take place unless bibliographic data is supplied, either through an external file specified using the [`--bibliography`](https://pandoc.org/MANUAL.html#option--bibliography) option or the `bibliography` field in metadata, or via a `references` section in metadata containing a list of citations in CSL YAML format with Markdown formatting.

We would like to set the "`references` section in metadata containing a list of citations in CSL YAML format", such that the subsequent citeproc filter can use this data to render the bibliography / references section.

[Assigning](https://github.com/manubot/manubot/blob/01d69f066eaf6554111e6bcf197f7ee1fcfb240b/manubot/pandoc/cite_filter.py#L206) a lists of dicts to `doc.metadata["references"]` worked with panflute 1.12.5, but not after upgrade to 2.0.4. I thought perhaps that `doc.metadata` intends to perform the necessary type conversions to pandoc-types upon assignment.

**Comment by sergiocorreia** [comment]
TBH I can't find any changes in the recent commits related to metadata or citations, so I'm not sure why it breaks with panflute 2.

> We would like to set the "references section in metadata containing a list of citations in CSL YAML format", such that the subsequent citeproc filter can use this data to render the bibliography / references section.

I think then what you need is a way to create the CSL YAML format text from the Cite/Citation objects. I'm not that familiar with the CSL YAML format though...

**Comment by dhimmel** [comment]
When running the pandoc-manubot-cite filter with panflute 1.12.5, here is the what happens after we set `doc.metadata["references"]` to a list of dicts:

`doc.metadata["references"]` returns

```python
MetaList(MetaMap('URL' 'author' 'container-title' 'id' 'issued' 'title' 'type' 'volume' 'note') MetaMap('type' 'id' 'author' 'issued' 'container-title' 'DOI' 'volume' 'issue' 'page' 'publisher' 'title' 'URL' 'note') MetaMap('type' 'id' 'author' 'issued' 'container-title' 'DOI' 'volume' 'issue' 'page' 'publisher' 'title' 'URL' 'PMCID' 'PMID' 'note') MetaMap('type' 'id' 'author' 'issued' 'container-title' 'DOI' 'volume' 'page' 'publisher' 'title' 'URL' 'PMCID' 'PMID' 'note') MetaMap('title' 'volume' 'issue' 'page' 'container-title' 'container-title-short' 'ISSN' 'issued' 'author' 'PMID' 'DOI' 'abstract' 'URL' 'type' 'id' 'note') MetaMap('container-title' 'id' 'issued' 'title' 'type' 'note') MetaMap('id' 'URL' 'title' 'container-title' 'issued' 'author' 'type' 'note') MetaMap('id' 'type' 'title' 'container-title' 'abstract' 'URL' 'shortTitle' 'language' 'accessed' 'note') MetaMap('id' 'type' 'title' 'publisher' 'source' 'URL' 'language' 'author' 'issued' 'accessed' 'note') MetaMap('id' 'type' 'title' 'source' 'abstract' 'URL' 'language' 'author' 'issued' 'accessed' 'note'))
```

`doc.metadata["references"][0]` returns 

```python
MetaMap('URL' 'author' 'container-title' 'id' 'issued' 'title' 'type' 'volume' 'note')
```

So panflute has converted the Python types to Pandoc types. These then are exported from the filter as JSON like:

```json
{
  "pandoc-api-version": [
    1,
    20
  ],
  "meta": {
    "manubot-log-level": {
      "t": "MetaInlines",
      "c": [
        {
          "t": "Str",
          "c": "INFO"
        }
      ]
    },
    "references": {
      "t": "MetaList",
      "c": [
        {
          "t": "MetaMap",
          "c": {
            "URL": {
              "t": "MetaString",
              "c": "http://arxiv.org/abs/1407.3561"
            },
            "author": {
              "t": "MetaList",
              "c": [
                {
                  "t": "MetaMap",
                  "c": {
                    "family": {
                      "t": "MetaString",
                      "c": "Benet"
                    },
                    "given": {
                      "t": "MetaString",
                      "c": "Juan"
                    }
                  }
                }
              ]
            },
            "container-title": {
              "t": "MetaString",
              "c": "CoRR"
            },
            "id": {
              "t": "MetaString",
              "c": "nkzHjOdS"
            },
```

Does panflute have a method for us to explicitly convert the list of dicts to Pandoc types? Perhaps then we could get this to work with panflue >= 2.

**Comment by sergiocorreia** [comment]
If I understand correctly, your example show how the data looks after it's exported by panflute to JSON.

How _should_ it look if you set it up as within the markdown metadata and export it to JSON using only panflute? I want to understand the diff between how it's looking and how it should look

**Comment by dhimmel** [comment]
> I want to understand the diff between how it's looking and how it should look

There is no issue with how the data looks in the comment above (which is from panflute 1.12.5). The only issue is the `builtin2meta` error that prevents the assignment at `doc.metadata["references"] = citations.csl_items` from working. Posted the root cause of the issue at https://github.com/sergiocorreia/panflute/issues/166

**Comment by dhimmel** [comment]
Pandoc replaced pandoc-citeproc with [citeproc](https://github.com/jgm/citeproc) in pandoc 2.11. From [release notes](https://github.com/jgm/pandoc/releases/tag/2.11):

> - only some of the writers (HTML, ms, LaTeX) properly interpret CSL display styles. You should get decent output in all formats (at least as good as with pandoc-citeproc), but indentation and block-alignment may not be right.

See the bibliography from 3cb9d02:

image

> - Some of the bibliography formats supported by pandoc-citeproc (via hs-bibutils) are no longer supported: Copac, EndNote, ISI, MEDLINE, MODS, and RIS. If you use one of these formats, you may use the bibutils utility to convert to BibLaTeX. We now support only BibTeX, BibLaTeX, CSL JSON, and pandoc’s YAML/Markdown analogue of CSL JSON.

> -   Add `csljson` as and input and output format. This allows pandoc to convert between `csljson` and other bibliography formats (e.g. `-f csljson -t markdown -s` or `-f bibtex -t csljson`), and to generate formatted versions of CSL JSON bibliographies (e.g., `pandoc -f csljson --citeproc pl.json -o pl.pdf`).

> -   Added `bibtex`, `biblatex` as input formats. This allows pandoc to convert between BibLaTeX and BibTeX and other bibliography formats, and to generated formatted versions of BibTeX/BibLaTeX bibliographies (e.g., `pandoc -f biblatex --citeproc pl.bib -o pl.pdf`).

So I think we need a little more work to ensure the reference formatting and loading bibliographies from alternative formats still works.

**Comment by dhimmel** [comment]
From 2.11 changelog:

> Add CSS to default HTML template (#6601, Mauro Bieg). This greatly improves the default typography in pandoc's HTML output. The CSS is sensitive to a number of variables (e.g. `mainfont`, `fontsize`, `linestretch`): see the manual for details. To restore the earlier, more spartan output, you can disable this with `-M document-css=false`.

In https://github.com/manubot/rootstock/pull/386/commits/39010a002534db2528250bc129ed7a64b24ef206, I set `document-css=false` which fixed the multiple CSS styles causing the PDF to have incorrect margins.

But we still need to update our CSS to add newlines to the references: see https://github.com/jgm/pandoc/issues/6921. Also might need to update our CSL style to make each reference line a block. Then our CSS style will add a break between blocks.

**Pull request closed without merging**
